ALTER TABLE farms ADD COLUMN IF NOT EXISTS farm_address VARCHAR(255) NULL;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS latitude DOUBLE NULL;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS longitude DOUBLE NULL;
ALTER TABLE farms ADD COLUMN IF NOT EXISTS location_last_updated DATETIME(6) NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_farm_address VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_latitude DOUBLE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pending_longitude DOUBLE NULL;
